#消费者
spring.application.name: spring-cloud-consumer
server.port: 10002
eureka.instance.instance-id: 127.0.0.1:${server.port}
eureka.client.serviceUrl.defaultZone: http://127.0.0.1:8002/eureka/,http://127.0.0.1:8001/eureka/
feign.hystrix.enabled: true
spring.main.allow-bean-definition-overriding: true

