##端口号
# Tomcat
server:
    tomcat:
        max-threads: 1000
        min-spare-threads: 10
    port: 8199
    servlet:
        context-path: /es

spring:
     data:
            elasticsearch:
                # 集群名
                cluster-name: elasticsearch
                # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
                # cluster-nodes: 10.10.2.139:9300
                cluster-nodes: 10.10.2.139:9300
                # 是否本地连接
                local: false
                repositories:
                 # 仓库中数据存储
                enabled: true

