spring:
    redis:
       timeout: 6000ms
       password:  
       cluster:
         max-redirects: 3   # 获取失败 最大重定向次数  
         nodes:
            - 10.10.2.139:7001
            - 10.10.2.139:7002
            - 10.10.2.139:7003
            - 10.10.2.139:7004
            - 10.10.2.139:7005
            - 10.10.2.139:7000
       jedis:
          pool:
             max-active: 1000             #连接池最大的连接数，若使用负值表示没有限制
             max-wait: 10s                 #连接池最大阻塞等待时间
             max-idle: 100                 #最大空闲连接数
             min-idle: 10
